gpg: Checking for the return code when signing
It seems that gpg2.1 does not necessarily send GOOD_PASSPHRASE when the
agent has a cached passphrase.

In fact, I can't produce two signatures because of the following
exception:

File "/tmp/gks-foo-install/local/lib/python2.7/site-
packages/gnome_keysign-0.6-py2.7.egg/monkeysign/gpg.py", line 510, in
sign_key
    raise GpgRuntimeError(self.context.returncode, _('unable to prompt
for passphrase, is gpg-agent running?'))
monkeysign.gpg.GpgRuntimeError: [Errno 0] unable to prompt for
passphrase, is gpg-agent running?

We can see the Errno 0. According to the man page, that's no problem,
though.  The modification appears to work with both, gpg1.4 and gpg2.1.
I haven't checked 2.0, though.