fix a transient error in unit tests
in some cases, i would see the following backtrace:

Traceback (most recent call last):
  File "/home/anarcat/src/monkeysign/tests/test_gpg.py", line 123, in tearDown
    shutil.rmtree(self.tmp)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 2] Aucun fichier ou dossier de ce type: '/tmp/pygpg-oszhAA/.#lk0x12d5bb0.angela.6377'

it looks like a socket that was present when the rmtree started, but
was automatically removed before it completed.

we just ignore those errors.